docker pull elixir
docker pull swift
docker pull groovy
docker pull rust
docker pull python
docker pull perl
docker pull golang
docker pull r-base
docker pull haskell
docker pull node
docker pull alpine
docker pull ruby
docker pull icode-gcc
docker pull php
docker pull openjdk
docker pull python
docker pull hello-world
docker pull gcc